# - name: install pip
#   apt:
#     name: python-pip
#     state: present

- name: pip install docker-py
  pip:
    name:
      - docker
      - docker-compose
      
- name: log registry token
  shell:
    cmd: docker login registry.gitlab.com/jordanmom/test -u Jordanmom -p glpat-WyXaZ-_sLV-j8y-tH8A6

- name: run container
  docker_container:
    name: backend
    image: "{{ image }}"
    ports: 5252:5252
    state: started
    
